//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mainForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.IssueTrans = new HashSet<IssueTran>();
            this.Reservations = new HashSet<Reservation>();
            this.StockAdjustments = new HashSet<StockAdjustment>();
            this.Authors = new HashSet<Author>();
        }
    
        public int BookID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string PublisherID { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string Language { get; set; }
        public string BookType { get; set; }
        public string Location { get; set; }
        public short TotalStock { get; set; }
        public short QtyLoaned { get; set; }
        public short RecommendedAge { get; set; }
        public string ISBN { get; set; }
        public short QtyReserved { get; set; }
    
        public virtual Publisher Publisher { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueTran> IssueTrans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockAdjustment> StockAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Author> Authors { get; set; }
    }
}
