//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mainForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueTran
    {
        public string TransactionID { get; set; }
        public string MemberID { get; set; }
        public int BookID { get; set; }
        public System.DateTime DateIssue { get; set; }
        public System.DateTime DateDue { get; set; }
        public System.DateTime DateReturned { get; set; }
        public string LoanStatus { get; set; }
        public string Remarks { get; set; }
        public string ExtensionStatus { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Member Member { get; set; }
    }
}
